/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaires;

import java.awt.Color;
import java.awt.Component;
import java.awt.ScrollPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author MECHACK
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgP = new javax.swing.JPanel();
        Pvertical = new javax.swing.JPanel();
        BtnAgent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnDirection = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnDivision = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnGrade = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        BtnConnexion = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        BtnPresence = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        BtnOption = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ScrollPne = new javax.swing.JScrollPane();
        OptionA = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnPointagePr = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BtnLPJ = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        BtnLPI = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BtnPointageS = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BtnLPM = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LblExit = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BgP.setBackground(new java.awt.Color(255, 255, 255));
        BgP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BgPMouseDragged(evt);
            }
        });
        BgP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BgPMousePressed(evt);
            }
        });
        BgP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pvertical.setBackground(new java.awt.Color(54, 33, 89));
        Pvertical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAgent.setBackground(new java.awt.Color(64, 43, 100));
        BtnAgent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnAgentMouseMoved(evt);
            }
        });
        BtnAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgentMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Admin_30px_3.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Agent");

        javax.swing.GroupLayout BtnAgentLayout = new javax.swing.GroupLayout(BtnAgent);
        BtnAgent.setLayout(BtnAgentLayout);
        BtnAgentLayout.setHorizontalGroup(
            BtnAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        BtnAgentLayout.setVerticalGroup(
            BtnAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAgentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, 40));

        BtnDirection.setBackground(new java.awt.Color(64, 43, 100));
        BtnDirection.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnDirectionMouseMoved(evt);
            }
        });
        BtnDirection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDirectionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnDirectionMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Department_30px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Direction");

        javax.swing.GroupLayout BtnDirectionLayout = new javax.swing.GroupLayout(BtnDirection);
        BtnDirection.setLayout(BtnDirectionLayout);
        BtnDirectionLayout.setHorizontalGroup(
            BtnDirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnDirectionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        BtnDirectionLayout.setVerticalGroup(
            BtnDirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnDirectionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnDirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnDirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        BtnDivision.setBackground(new java.awt.Color(64, 43, 100));
        BtnDivision.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnDivisionMouseMoved(evt);
            }
        });
        BtnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDivisionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnDivisionMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bureau_30px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Division");

        javax.swing.GroupLayout BtnDivisionLayout = new javax.swing.GroupLayout(BtnDivision);
        BtnDivision.setLayout(BtnDivisionLayout);
        BtnDivisionLayout.setHorizontalGroup(
            BtnDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnDivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        BtnDivisionLayout.setVerticalGroup(
            BtnDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnDivisionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 40));

        BtnGrade.setBackground(new java.awt.Color(64, 43, 100));
        BtnGrade.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnGradeMouseMoved(evt);
            }
        });
        BtnGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGradeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGradeMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Numerical_Sorting_30px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Grade");

        javax.swing.GroupLayout BtnGradeLayout = new javax.swing.GroupLayout(BtnGrade);
        BtnGrade.setLayout(BtnGradeLayout);
        BtnGradeLayout.setHorizontalGroup(
            BtnGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        BtnGradeLayout.setVerticalGroup(
            BtnGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnGradeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("MENU");
        Pvertical.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));
        Pvertical.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pointage de presences");
        Pvertical.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        BtnConnexion.setBackground(new java.awt.Color(64, 43, 100));
        BtnConnexion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnConnexionMouseMoved(evt);
            }
        });
        BtnConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConnexionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnConnexionMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Enter_30px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Connexion");

        javax.swing.GroupLayout BtnConnexionLayout = new javax.swing.GroupLayout(BtnConnexion);
        BtnConnexion.setLayout(BtnConnexionLayout);
        BtnConnexionLayout.setHorizontalGroup(
            BtnConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(29, 29, 29)
                .addComponent(jLabel25)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        BtnConnexionLayout.setVerticalGroup(
            BtnConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnConnexionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnConnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 40));

        BtnPresence.setBackground(new java.awt.Color(64, 43, 100));
        BtnPresence.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnPresenceMouseMoved(evt);
            }
        });
        BtnPresence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPresenceMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPresenceMouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_List_30px.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Presences");

        javax.swing.GroupLayout BtnPresenceLayout = new javax.swing.GroupLayout(BtnPresence);
        BtnPresence.setLayout(BtnPresenceLayout);
        BtnPresenceLayout.setHorizontalGroup(
            BtnPresenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPresenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(29, 29, 29)
                .addComponent(jLabel27)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        BtnPresenceLayout.setVerticalGroup(
            BtnPresenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPresenceLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnPresenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnPresence, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 190, 40));

        BtnOption.setBackground(new java.awt.Color(85, 65, 118));
        BtnOption.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BtnOptionMouseMoved(evt);
            }
        });
        BtnOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnOptionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnOptionMouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Menu_30px.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Options");

        javax.swing.GroupLayout BtnOptionLayout = new javax.swing.GroupLayout(BtnOption);
        BtnOption.setLayout(BtnOptionLayout);
        BtnOptionLayout.setHorizontalGroup(
            BtnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(37, 37, 37)
                .addComponent(jLabel29)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        BtnOptionLayout.setVerticalGroup(
            BtnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnOptionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(BtnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pvertical.add(BtnOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, 40));

        BgP.add(Pvertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 560));

        ScrollPne.setBackground(new java.awt.Color(255, 255, 255));

        OptionA.setBackground(new java.awt.Color(255, 255, 255));
        OptionA.setMinimumSize(new java.awt.Dimension(700, 450));
        OptionA.setPreferredSize(new java.awt.Dimension(700, 400));
        OptionA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(122, 71, 222));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Options de l'application");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 320, 10));

        OptionA.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        BtnPointagePr.setBackground(new java.awt.Color(85, 45, 118));
        BtnPointagePr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPointagePrMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Pointage de presence");

        javax.swing.GroupLayout BtnPointagePrLayout = new javax.swing.GroupLayout(BtnPointagePr);
        BtnPointagePr.setLayout(BtnPointagePrLayout);
        BtnPointagePrLayout.setHorizontalGroup(
            BtnPointagePrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPointagePrLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        BtnPointagePrLayout.setVerticalGroup(
            BtnPointagePrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPointagePrLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionA.add(BtnPointagePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Time & Date.png"))); // NOI18N
        OptionA.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 140, 130));

        BtnLPJ.setBackground(new java.awt.Color(85, 45, 118));
        BtnLPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLPJMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Liste de presence hebdomadaire");

        javax.swing.GroupLayout BtnLPJLayout = new javax.swing.GroupLayout(BtnLPJ);
        BtnLPJ.setLayout(BtnLPJLayout);
        BtnLPJLayout.setHorizontalGroup(
            BtnLPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLPJLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        BtnLPJLayout.setVerticalGroup(
            BtnLPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLPJLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionA.add(BtnLPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 240, 40));

        BtnLPI.setBackground(new java.awt.Color(85, 45, 118));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Liste de presence individuelle");

        javax.swing.GroupLayout BtnLPILayout = new javax.swing.GroupLayout(BtnLPI);
        BtnLPI.setLayout(BtnLPILayout);
        BtnLPILayout.setHorizontalGroup(
            BtnLPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLPILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        BtnLPILayout.setVerticalGroup(
            BtnLPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLPILayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionA.add(BtnLPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Time & Date.png"))); // NOI18N
        OptionA.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 140, 130));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webcam.png"))); // NOI18N
        OptionA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 110));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Webcam.png"))); // NOI18N
        OptionA.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 140, 110));

        BtnPointageS.setBackground(new java.awt.Color(85, 45, 118));
        BtnPointageS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPointageSMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Pointage de sortie");

        javax.swing.GroupLayout BtnPointageSLayout = new javax.swing.GroupLayout(BtnPointageS);
        BtnPointageS.setLayout(BtnPointageSLayout);
        BtnPointageSLayout.setHorizontalGroup(
            BtnPointageSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPointageSLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel19)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        BtnPointageSLayout.setVerticalGroup(
            BtnPointageSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPointageSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionA.add(BtnPointageS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 220, 40));

        BtnLPM.setBackground(new java.awt.Color(85, 45, 118));
        BtnLPM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLPMMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Liste de presence mensuelle");

        javax.swing.GroupLayout BtnLPMLayout = new javax.swing.GroupLayout(BtnLPM);
        BtnLPM.setLayout(BtnLPMLayout);
        BtnLPMLayout.setHorizontalGroup(
            BtnLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnLPMLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        BtnLPMLayout.setVerticalGroup(
            BtnLPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLPMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionA.add(BtnLPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 220, -1));

        ScrollPne.setViewportView(OptionA);

        BgP.add(ScrollPne, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 840, 500));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_Math__30px.png"))); // NOI18N
        BgP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, 20));

        LblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblExit.setForeground(new java.awt.Color(204, 204, 204));
        LblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_30px.png"))); // NOI18N
        LblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblExitMouseClicked(evt);
            }
        });
        BgP.add(LblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Pointage de presences");
        BgP.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1030, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOptionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOptionMouseMoved
        // TODO add your handling code here:
        setColor(BtnOption);
        resetColor(BtnDirection);
        resetColor(BtnAgent);
        resetColor(BtnDivision);
        resetColor(BtnConnexion);
        resetColor(BtnPresence);
        resetColor(BtnGrade);
    }//GEN-LAST:event_BtnOptionMouseMoved

    private void BtnDirectionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDirectionMouseMoved
        // TODO add your handling code here:
        setColor(BtnDirection);
        resetColor(BtnGrade);
        resetColor(BtnAgent);
        resetColor(BtnDivision);
        resetColor(BtnConnexion);
        resetColor(BtnPresence);
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnDirectionMouseMoved

    private void BtnDivisionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDivisionMouseMoved
        // TODO add your handling code here:
        setColor(BtnDivision);
        resetColor(BtnDirection);
        resetColor(BtnAgent);
        resetColor(BtnGrade);
        resetColor(BtnConnexion);
        resetColor(BtnPresence);
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnDivisionMouseMoved

    private void BtnGradeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGradeMouseMoved
        // TODO add your handling code here:
        setColor(BtnGrade);
        resetColor(BtnDirection);
        resetColor(BtnAgent);
        resetColor(BtnDivision);
        resetColor(BtnConnexion);
        resetColor(BtnPresence);
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnGradeMouseMoved

    private void BtnConnexionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConnexionMouseMoved
        // TODO add your handling code here:
        setColor(BtnConnexion);
        resetColor(BtnDirection);
        resetColor(BtnAgent);
        resetColor(BtnDivision);
        resetColor(BtnGrade);
        resetColor(BtnPresence);
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnConnexionMouseMoved

    private void BtnPresenceMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPresenceMouseMoved
        // TODO add your handling code here:
        setColor(BtnPresence);
        resetColor(BtnDirection);
        resetColor(BtnAgent);
        resetColor(BtnDivision);
        resetColor(BtnConnexion);
        resetColor(BtnGrade);
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnPresenceMouseMoved

    private void BtnAgentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgentMouseMoved
        // TODO add your handling code here:
        setColor(BtnAgent);
        resetColor(BtnDirection);
        resetColor(BtnGrade);
        resetColor(BtnDivision);
        resetColor(BtnConnexion);
        resetColor(BtnPresence);
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnAgentMouseMoved

    private void BtnOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOptionMouseExited
        // TODO add your handling code here:
        resetColor(BtnOption);
    }//GEN-LAST:event_BtnOptionMouseExited

    private void BtnDirectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDirectionMouseExited
        // TODO add your handling code here:
        resetColor(BtnDirection);
    }//GEN-LAST:event_BtnDirectionMouseExited

    private void BtnDivisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDivisionMouseExited
        // TODO add your handling code here:
        resetColor(BtnDivision);
    }//GEN-LAST:event_BtnDivisionMouseExited

    private void BtnGradeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGradeMouseExited
        // TODO add your handling code here:
        resetColor(BtnGrade);
    }//GEN-LAST:event_BtnGradeMouseExited

    private void BtnConnexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConnexionMouseExited
        // TODO add your handling code here:
        resetColor(BtnConnexion);
    }//GEN-LAST:event_BtnConnexionMouseExited

    private void BtnPresenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPresenceMouseExited
        // TODO add your handling code here:
        resetColor(BtnPresence);
    }//GEN-LAST:event_BtnPresenceMouseExited

    private void BtnAgentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgentMouseExited
        // TODO add your handling code here:
        resetColor(BtnAgent);
    }//GEN-LAST:event_BtnAgentMouseExited

    private void LblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExitMouseClicked
        // TODO add your handling code here:
        int rep = JOptionPane.showConfirmDialog(null, "Etes-vous sur de voiloir fermer l'applicaion ??", "EXIT", JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_LblExitMouseClicked

    private void BgPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BgPMousePressed

    private void BgPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);

    }//GEN-LAST:event_BgPMouseDragged

    private void BtnOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOptionMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(OptionA);
    }//GEN-LAST:event_BtnOptionMouseClicked

    private void BtnAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgentMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new Pnagent());
    }//GEN-LAST:event_BtnAgentMouseClicked

    private void BtnDirectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDirectionMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new Pndirection());
    }//GEN-LAST:event_BtnDirectionMouseClicked

    private void BtnDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDivisionMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new Pndivision());
    }//GEN-LAST:event_BtnDivisionMouseClicked

    private void BtnGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGradeMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new Pngrade());
    }//GEN-LAST:event_BtnGradeMouseClicked

    private void BtnConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConnexionMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.hide();
    }//GEN-LAST:event_BtnConnexionMouseClicked

    private void BtnPresenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPresenceMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new Presence());
    }//GEN-LAST:event_BtnPresenceMouseClicked

    private void BtnPointagePrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPointagePrMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new PnPointerPresence());
    }//GEN-LAST:event_BtnPointagePrMouseClicked

    private void BtnLPJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLPJMouseClicked
        // TODO add your handling code here:
          ScrollPne.setViewportView(new PnListePresenceHebdomadaire()); 
    }//GEN-LAST:event_BtnLPJMouseClicked

    private void BtnPointageSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPointageSMouseClicked
        // TODO add your handling code here:
         ScrollPne.setViewportView(new PnPointerPresence());
    }//GEN-LAST:event_BtnPointageSMouseClicked

    private void BtnLPMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLPMMouseClicked
        // TODO add your handling code here:
        ScrollPne.setViewportView(new PnListPMensuel());  
    }//GEN-LAST:event_BtnLPMMouseClicked
    int xx;
    int xy;

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgP;
    private javax.swing.JPanel BtnAgent;
    private javax.swing.JPanel BtnConnexion;
    private javax.swing.JPanel BtnDirection;
    private javax.swing.JPanel BtnDivision;
    private javax.swing.JPanel BtnGrade;
    private javax.swing.JPanel BtnLPI;
    private javax.swing.JPanel BtnLPJ;
    private javax.swing.JPanel BtnLPM;
    private javax.swing.JPanel BtnOption;
    private javax.swing.JPanel BtnPointagePr;
    private javax.swing.JPanel BtnPointageS;
    private javax.swing.JPanel BtnPresence;
    private javax.swing.JLabel LblExit;
    private javax.swing.JPanel OptionA;
    private javax.swing.JPanel Pvertical;
    private javax.swing.JScrollPane ScrollPne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
