/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaires;

import Entites.Agent;
import Entites.Division;
import Entites.Grade;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author MECHACK
 */
public class Pnagent extends javax.swing.JPanel {

    /**
     * Creates new form Pnagent
     */
    Agent ag = new Agent();
    Division dv = new Division();
    Grade grd = new Grade();

    public Pnagent() {
        initComponents();
        ag.Remplir(jTable1, "select matricule,nom,postnom,sexe,id_grade,id_division from AGENT");
        dv.Charger(CmbDivision);
        grd.Charger(CmbGrade);
    }

    void Nettoyer() {
        TxtMatr.setText("");
        TxtNom.setText("");
        TxtPostnm.setText("");
        CmbSexe.setSelectedItem("");
        CmbGrade.setSelectedItem("");
        CmbDivision.setSelectedItem("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtRecherche = new javax.swing.JTextField();
        BtnCapture = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BtnSave = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnClean = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxtMatr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtPostnm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CmbSexe = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        CmbDivision = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        CmbGrade = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        LblImage = new javax.swing.JLabel();
        BtnCapture1 = new javax.swing.JButton();
        BtnCapture2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        BgP.setBackground(new java.awt.Color(255, 255, 255));
        BgP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 71, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fénetre AGENT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 390, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 10));

        BgP.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agents Enregistrés", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        BgP.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 530, 200));

        TxtRecherche.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BgP.add(TxtRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, -1));

        BtnCapture.setBackground(new java.awt.Color(0, 0, 0));
        BtnCapture.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnCapture.setForeground(new java.awt.Color(255, 255, 255));
        BtnCapture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Download_30px.png"))); // NOI18N
        BtnCapture.setText("Charger");
        BgP.add(BtnCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_26px.png"))); // NOI18N
        BgP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 40, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commandes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 18))); // NOI18N

        BtnSave.setBackground(new java.awt.Color(0, 0, 0));
        BtnSave.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnSave.setForeground(new java.awt.Color(255, 255, 255));
        BtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_25px.png"))); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        BtnUpdate.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Available_Updates_26px.png"))); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(0, 0, 0));
        BtnDelete.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_25px.png"))); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnClean.setBackground(new java.awt.Color(0, 0, 0));
        BtnClean.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnClean.setForeground(new java.awt.Color(255, 255, 255));
        BtnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Broom_25px.png"))); // NOI18N
        BtnClean.setText("Clean");
        BtnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnDelete)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(BtnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(BtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDelete)
                    .addComponent(BtnClean)
                    .addComponent(BtnUpdate))
                .addContainerGap())
        );

        BgP.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 450, 120));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coordonnées", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel5.setText("Matricule");

        TxtMatr.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel4.setText("Nom");

        TxtNom.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel3.setText("Postnom");

        TxtPostnm.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel2.setText("Sexe");

        CmbSexe.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        CmbSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel1.setText("Division");

        CmbDivision.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel6.setText("Grade");

        CmbGrade.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(TxtMatr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(TxtPostnm, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(CmbSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(CmbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TxtMatr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPostnm, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CmbSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CmbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        BgP.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 370, 280));

        jScrollPane2.setViewportView(LblImage);

        BgP.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 260, 190));

        BtnCapture1.setBackground(new java.awt.Color(0, 0, 0));
        BtnCapture1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnCapture1.setForeground(new java.awt.Color(255, 255, 255));
        BtnCapture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Screenshot_30px.png"))); // NOI18N
        BtnCapture1.setText("Capturer");
        BgP.add(BtnCapture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, 40));

        BtnCapture2.setBackground(new java.awt.Color(0, 0, 0));
        BtnCapture2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        BtnCapture2.setForeground(new java.awt.Color(255, 255, 255));
        BtnCapture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Detective_30px.png"))); // NOI18N
        BtnCapture2.setText("Detecter");
        BgP.add(BtnCapture2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, 40));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        BgP.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 160, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BgP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        if (TxtMatr.getText().equals("") || TxtNom.getText().equals("") || TxtPostnm.getText().equals("")
                || CmbSexe.getSelectedItem().equals("") || CmbGrade.getSelectedItem().equals("") || CmbDivision.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
        } else {
            ag.setMatr(TxtMatr.getText());
            ag.setNom(TxtNom.getText());
            ag.setPostnom(TxtPostnm.getText());
            ag.setSexe(CmbSexe.getSelectedItem().toString());
            ag.setIdgrade(CmbGrade.getSelectedItem().toString());
            ag.setIddivision(CmbDivision.getSelectedItem().toString());
            ag.setPhoto((Image) LblImage.getIcon());
            ag.Ajouter();
            ag.Remplir(jTable1, "select matricule,nom,postnom,sexe,id_grade,id_division from AGENT");
            Nettoyer();
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        int rep = JOptionPane.showConfirmDialog(null, "Etes-vous sur de voiloir MODIFIER ??", "MODIFICATION", JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            if (TxtMatr.getText().equals("") || TxtNom.getText().equals("") || TxtPostnm.getText().equals("")
                    || CmbSexe.getSelectedItem().equals("") || CmbGrade.getSelectedItem().equals("") || CmbDivision.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Veuillez selectionner une ligne", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
            } else {
                ag.setMatr(TxtMatr.getText());
                ag.setNom(TxtNom.getText());
                ag.setPostnom(TxtPostnm.getText());
                ag.setSexe(CmbSexe.getSelectedItem().toString());
                ag.setIdgrade(CmbGrade.getSelectedItem().toString());
                ag.setIddivision(CmbDivision.getSelectedItem().toString());
                ag.setPhoto((Image) LblImage.getIcon());
                ag.Modifier();
                ag.Remplir(jTable1, "select matricule,nom,postnom,sexe,id_grade,id_division from AGENT");
                Nettoyer();
            }

        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        int rep = JOptionPane.showConfirmDialog(null, "Etes-vous sur de voiloir SUPPRIMER ??", "SUPPRESSION", JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION) {
            if (TxtMatr.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Veuillez Saisir l'identifiant de l'agent à supprimer", "ATTENTION!!", JOptionPane.ERROR_MESSAGE);
            } else {
                ag.setMatr(TxtMatr.getText());
                ag.Supprimer();
                ag.Remplir(jTable1, "select matricule,nom,postnom,sexe,id_grade,id_division from AGENT");
                Nettoyer();
            }

        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();
        TxtMatr.setText(jTable1.getValueAt(ligne, 0).toString());
        TxtNom.setText(jTable1.getValueAt(ligne, 1).toString());
        TxtPostnm.setText(jTable1.getValueAt(ligne, 2).toString());
        CmbSexe.setSelectedItem(jTable1.getValueAt(ligne, 3));
        CmbGrade.setSelectedItem(jTable1.getValueAt(ligne, 4));
        CmbDivision.setSelectedItem(jTable1.getValueAt(ligne, 5));

    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCleanActionPerformed
        // TODO add your handling code here:
        Nettoyer();
                
    }//GEN-LAST:event_BtnCleanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgP;
    private javax.swing.JButton BtnCapture;
    private javax.swing.JButton BtnCapture1;
    private javax.swing.JButton BtnCapture2;
    private javax.swing.JButton BtnClean;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox CmbDivision;
    private javax.swing.JComboBox CmbGrade;
    private javax.swing.JComboBox CmbSexe;
    private javax.swing.JLabel LblImage;
    private javax.swing.JTextField TxtMatr;
    private javax.swing.JTextField TxtNom;
    private javax.swing.JTextField TxtPostnm;
    private javax.swing.JTextField TxtRecherche;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
